### ISSUE TITLE
Failure to add_cookie() for firefox geckodriver in django-selenium-login

### ISSUE THREAD

**Issue by pakal** [feffe/django-selenium-login#5]
For some reason, on firefox, when the force_login() attempts to set a cookie like this on firefox 67 (geckodriver v0.24.0):

>  {'domain': 'localhost', 'name': 'sessionid', 'path': '/', 'value': 'bz8pd0zdsedi9oz'}

then it fails with an error :

> selenium.common.exceptions.UnableToSetCookieException: Message: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICookieManager.add]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: chrome://marionette/content/cookie.js :: cookie.add :: line 162"  data: no]

Removing the "domain" entry makes the add_cookie() call successful.

With Chrome driver, no problems.

It's visibly a bug of Firefox geckodriver, but maybe allow caller to force or disable the "domain" entry, to work around that bug?

**Comment by feffe** [comment]
For some reason domain names without dots are not accepted in the session cookie with Firefox. The domain is set using live_server.url. In the tests, I set the liveserver address to 127.0.0.1 for Firefox to get around this. For a quick solution, you can just use 127.0.0.1 instead of localhost for your tests, but I will also make a new release with the option not to set domain for session cookie.

**Comment by pakal** [comment]
Thanks for the workarounds  :)

 I opened https://github.com/mozilla/geckodriver/issues/1579 as a follow-up.

**Comment by feffe** [comment]
A new release 1.1.0 is now available with set_domain_in_session_cookie parameter for force_login
